FROM debian:latest

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential \
		gdb \
		vim \
		git \
		cmake \
		man \
		curl \
		sudo \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash ashaclem  \
	&& echo "ashaclem ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ashaclem

USER ashaclem
WORKDIR /home/ashaclem/s21

CMD ["/bin/bash"]
